dist: bionic

language: php

php:
  - 7.3
  - 7.4
  - 8.0
  - nightly

branches:
  only:
    - master
    - /^\d+\.\d+$/

matrix:
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || true
  - composer selfupdate

install: composer update --prefer-source --no-interaction

script:
  - composer check-platform-reqs
  - vendor/bin/phpunit --debug
