name: "Coding Standards"

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  coding-standards:
    name: "Coding Standards"
    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        php-version:
          - "7.3"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          tools: "cs2pr"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"

      - name: "Install php-cs-fixer"
        run: composer require "friendsofphp/php-cs-fixer:^2.16"

      - name: "Run php-cs-fixer"
        run: "vendor/bin/php-cs-fixer fix --diff --dry-run -v"
